#!/bin/sh /etc/rc.common

START=50

run_switch_lan_play()
{
    local enable
    config_get_bool enable $1 enable
    
    if [ $enable ]; then
        local relay_server_ip
        local relay_server_port
        local ifname
        
        config_get relay_server_ip $1 relay_server_ip
        config_get relay_server_port $1 relay_server_port
        config_get ifname $1 ifname

        lan-play --relay-server-addr $relay_server_ip:$relay_server_port --netif $ifname &
        
        echo "Switch Lan Play Client has started."
	else
        	stop
	fi
}

start()
{
    config_load switch-lan-play
    config_foreach run_switch_lan_play server
}

stop()
{
    pgrep lan-play | xargs -r kill -9
    
    echo "Switch Lan Play Client has stopped."
}
restart()
{
	stop
	start
}